services:
  db_redis:
    image: redis
    container_name: redis_db

    environment:
      - REDIS_PASSWORD=password
      - REDIS_USER=user
      - REDIS_USER_PASSWORD=password

    volumes:
      - ./dbs/redis/data:/data
      - ./dbs/redis/confs/redis.conf:/usr/local/etc/redis/redis.conf

    restart: always

    ports:
      - 6379:6379

  db_mysql:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./dbs/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  web_nginx:
    image: nginx
    container_name: nginx_server

    volumes:
      - ./server/nginx/confs/:/etc/nginx/conf.d
      - ./server/nginx/html:/server/html

    restart: always

    ports:
      - 80:80


  web_apache:
    container_name: apache_server

    volumes:
      - ./server/apache/confs/apache2.conf:/etc/apache2/apache2.conf

      - ./server/apache/confs/access:/etc/apache2/access
      - ./server/apache/confs/sites-available:/etc/apache2/sites-available

      - ./server/apache/data:/server/data

    build:
      context: ./server/apache
      dockerfile: Dockerfile

    restart: always

    ports:
      - 8000:80
      
    depends_on:
      - db_mysql
      - db_redis

    command: ["sh", "-c", "php /server/data/init/init.php && apache2-foreground"]